esphome:
  name: esp32-test-1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "c6Ny0eTVbCcwiRmvTTrCBOW4SFa9bRg6cGHXT1rePeE="

ota:
  password: "462f0d26a704dacd265b60e1e479f5b7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Test-1 Fallback Hotspot"
    password: "su0wsF4WVPfv"

captive_portal:
    
esp32_ble_tracker:

sensor:
  - platform: xiaomi_lywsdcgq
    mac_address: "58:2d:34:33:51:AE"
    temperature:
      name: "LYWSDCGQ Temperature"
    humidity:
      name: "LYWSDCGQ Humidity"
    battery_level:
      name: "LYWSDCGQ Battery Level"